//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team09B_TEXT
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanRecord
    {
        public short LoanID { get; set; }
        public short MemberID { get; set; }
        public short BookID { get; set; }
        public System.DateTime DateLoan { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public string Record { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Member Member { get; set; }
    }
}
