//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA43Team09B_TEXT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchEngine
    {
        public short BookID { get; set; }
        public string ISBN { get; set; }
        public string BookTitle { get; set; }
        public string BookAuthor { get; set; }
        public string BookCategory { get; set; }
        public string BookStatus { get; set; }
    }
}
